"use strict";
const ANALYSIS_PLACEHOLDER='【请先连接大模型以获取准确分析】';
const $=id=>document.getElementById(id), token=window.APP_TOKEN;
let activeId=null, acquisition=null, R=null, review={notes:'',items:{}}, pollTimer, analysisTimer, loginTimer;
let evidenceIds=[], evidenceLimit=40, questionLimit=20, segmentLimit=20, chartKey='count',logScale=false;
const fmt=s=>Math.floor(s/60).toString().padStart(2,'0')+':'+Math.floor(s%60).toString().padStart(2,'0');
const names={metadata:'课程信息',danmaku:'弹幕快照',video:'音视频下载',video_validation:'媒体校验'};
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function button(text,fn){const b=el('button',text);b.onclick=fn;return b}
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Token':token},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d}
function wb(action,id=activeId){return '/api/workbench/'+id+'/'+action}
function fail(e){$('error').textContent=e.message||String(e)}
function metric(parent,title,value,detail){const d=el('div',undefined,'metric');d.append(el('span',title),el('strong',value),el('span',detail));$(parent).append(d)}
function drawAcquisition(d){acquisition=d;drawAcquisitionProgress(d);$('record').textContent=JSON.stringify(d,null,2);$('cards').replaceChildren();$('steps').replaceChildren();const a=d.artifacts||{};
if(a.metadata)metric('cards','课程时长',fmt(a.metadata.duration_s),'课程信息已获取');
if(a.danmaku)metric('cards','带时间戳弹幕',a.danmaku.valid_count.toLocaleString()+' 条','当次可用快照 · 已保存');
if(a.video)metric('cards','含音轨视频',a.video.width+' × '+a.video.height,(a.video.bytes/1048576).toFixed(1)+' MiB · 媒体已校验');
$('headline').textContent=['acquired','snapshot_acquired'].includes(d.status)?'已成功获取'+(a.video?'音视频、':'')+'课程信息与 '+(a.danmaku?.valid_count??0)+' 条弹幕':d.status==='running'?'正在获取课程素材…':'获取未全部完成：'+(d.error||d.status);
$('courseFacts').replaceChildren();for(const [name,value] of [['BV号',d.bvid],['分P',d.part?'P'+d.part:null],['CID',a.metadata?.cid],['本次获取会话',d.login_state==='local_session_supplied'?'使用本地登录会话':d.login_state==='no_session_supplied'?'未使用登录会话':null]]){if(value!==undefined&&value!==null){const pair=el('div');pair.append(el('dt',name),el('dd',String(value)));$('courseFacts').append(pair)}}$('course').textContent=d.title?d.title+' · P'+d.part:'';$('saved').textContent=d.observed_at?new Date(d.observed_at).toLocaleString()+' 快照':'';
for(const s of d.stages||[]){$('steps').append(el('span',(s.status==='completed'?'✓ ':s.status==='failed'?'! ':'◌ ')+(names[s.name]||s.name)+(s.status==='running'?' · 进行中':'')))}
$('fetch').disabled=d.status==='running';$('showComments').hidden=!a.danmaku;$('downloadComments').hidden=!a.danmaku;$('downloadComments').href='/api/acquisition/'+activeId+'/download';
$('analyze').disabled=!a.danmaku||d.status==='running';}
async function pollAcquisition(id){try{const d=await api('/api/acquisition/'+id);if(id!==activeId)return;drawAcquisition(d);if(d.status==='running')pollTimer=setTimeout(()=>pollAcquisition(id),1500);else loadCourses()}catch(e){if(id!==activeId)return;fail(e);$('acquisitionProgress').hidden=false;$('acquisitionProgress').dataset.state='unknown';$('acquisitionState').textContent='连接中断 · 暂时无法确认任务结果';$('progressDetail').textContent='后台任务可能仍在运行。重新检查状态即可，无需重复获取。';$('fileProgressArea').hidden=true;$('refreshAcquisition').hidden=false;$('fetch').disabled=false}}
async function selectCourse(id){clearTimeout(pollTimer);clearTimeout(analysisTimer);activeId=id;R=null;review={notes:'',items:{}};$('report').hidden=true;$('error').textContent='';$('analysisDetail').textContent='标签与问题识别仍需教师核查；当前不生成课程质量总分。';await pollAcquisition(id);await loadSyllabus(id);await pollAnalysis(id);}
async function loadCourses(){try{const d=await api('/api/courses');$('courseList').replaceChildren();for(const c of d.courses){$('courseList').append(button(c.title+' · '+(c.artifacts.danmaku.valid_count.toLocaleString())+' 条 · '+new Date(c.observed_at).toLocaleString(),()=>selectCourse(c.id).catch(fail)))}if(!d.courses.length)$('courseList').append(el('p','尚无已获取课程。'))}catch(e){fail(e)}}
$('fetch').onclick=async()=>{try{$('fetch').disabled=true;drawAcquisitionProgress({status:'running',stages:[]});$('progressDetail').textContent='正在提交获取请求…';const d=await api('/api/acquire',{url:$('url').value});await selectCourse(d.id)}catch(e){fail(e);drawAcquisitionProgress({status:'acquisition_failed',stages:[],error:'本次请求未启动：'+e.message});$('fetch').disabled=false}};
$('showComments').onclick=async()=>{try{if(R){showEvidence(R.comments.map(c=>c.id),'全部原始弹幕');return}const id=activeId;const d=await api('/api/acquisition/'+id+'/download');if(id!==activeId)return;showRaw(d.comments)}catch(e){fail(e)}};
let rawComments=null;
function showRaw(comments){rawComments=comments;showEvidence(comments.map(c=>c.id),'全部原始弹幕')}
async function startAnalysis(mode,transcript){if(!activeId)return;try{$('analyze').disabled=true;$('error').textContent='';const id=activeId;await api(wb(transcript?'import':'analyze'),transcript?{transcript}:{mode,provider:$('inferenceProvider').value,sample_size:$('sample100').checked?100:null,max_seconds:$('analysisRange').value?Number($('analysisRange').value):null});R=null;$('report').hidden=true;await pollAnalysis(id)}catch(e){fail(e);$('analyze').disabled=false}}
$('analyze').onclick=()=>startAnalysis(document.querySelector('input[name=mode]:checked').value);
let syllabusDocument=null,frameLimit=6;
async function loadSyllabus(id){try{const d=await api(wb('syllabus',id));if(id!==activeId)return;syllabusDocument=d.syllabus;$('syllabusText').value=syllabusDocument?.text||'';drawSyllabusStatus();if(R){R.syllabus=syllabusDocument;renderCurriculum()}}catch(e){$('syllabusStatus').textContent=e.message}}
function drawSyllabusStatus(){$('syllabusStatus').textContent=syllabusDocument?'已保存 '+syllabusDocument.filename+' · '+syllabusDocument.paragraph_count+' 段原文':'尚未导入教学大纲 · 支持 DOCX / TXT / Markdown，最大5MB'}
async function uploadSyllabus(name,bytes){if(!activeId)throw Error('请先获取或选择课程');if(bytes.length>5*1024*1024)throw Error('大纲文件不能超过5MB');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const id=activeId;const d=await api(wb('syllabus',id),{name,content:btoa(binary)});if(id!==activeId)return;syllabusDocument=d.syllabus;$('syllabusText').value=syllabusDocument.text;drawSyllabusStatus();if(R){R.syllabus=syllabusDocument;R.syllabus_stale=true;if(R.model_review)R.model_review.alignment=[];renderCurriculum();if(R.analysis_status==='model_preliminary')renderModelReport()}$('error').textContent=''}
$('importSyllabus').onclick=()=>$('syllabusFile').click();
$('syllabusFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{$('syllabusStatus').textContent='正在读取并保存大纲…';await uploadSyllabus(file.name,new Uint8Array(await file.arrayBuffer()))}catch(err){$('syllabusStatus').textContent='导入未完成：'+err.message}finally{e.target.value=''}};
$('saveSyllabus').onclick=async()=>{const b=$('saveSyllabus');b.disabled=true;try{await uploadSyllabus('教师教学大纲.txt',new TextEncoder().encode($('syllabusText').value))}catch(e){$('syllabusStatus').textContent='保存未完成：'+e.message}finally{b.disabled=false}};
function renderCurriculum(){const d=R?.syllabus;$('outlineParagraphs').replaceChildren();$('outlineReportStatus').textContent=d?d.filename+' · '+d.paragraph_count+' 段原文':'尚未提供教师教学大纲';if(!d){$('outlineParagraphs').append(el('p','请在上方导入教师教学大纲，或粘贴并保存原文。','muted'));return}for(const p of d.paragraphs){const item=el('div',undefined,'item');item.append(el('span',p.id,'muted small'),el('p',p.text));$('outlineParagraphs').append(item)}}
function renderMedia(){const frames=R.frames||[],m=R.media_summary||{};$('mediaFacts').textContent=frames.length?frames.length+' 张画面 · '+(m.transcript_segments??'已生成')+' 段转写草稿':'尚未处理音视频';$('frameGallery').replaceChildren();for(const [i,f] of frames.slice(0,frameLimit).entries()){const item=el('figure'),img=el('img');img.src=wb('frame')+'?index='+i;img.alt='课程画面 '+fmt(f.requested_time_s);img.loading='lazy';const b=button(fmt(f.requested_time_s)+' · 回看讲解',()=>seek(f.requested_time_s*1000));item.append(img,b);$('frameGallery').append(item)}if(!frames.length)$('frameGallery').append(el('p','选择“课镜音视频复盘”后，系统会直接处理已获取的视频并展示课程画面。','muted'));$('moreFrames').hidden=frames.length<=frameLimit}
$('moreFrames').onclick=()=>{frameLimit+=6;renderMedia()};
async function pollAnalysis(id){try{const s=await api(wb('status',id));if(id!==activeId)return;$('analysisState').textContent=s.stage;const running=s.status==='running';$('analyze').disabled=running||!acquisition?.artifacts?.danmaku;
if(s.media_progress){$('analysisDetail').textContent='完整课程转写：已处理 '+s.media_progress.completed_chunks+' / '+Math.ceil(s.media_progress.duration_s/300)+' 个分块。完成后提取画面并关联弹幕。'}
if(s.status==='failed'||s.status==='interrupted')$('analysisDetail').textContent=s.error||s.stage;
if(s.model_progress)$('analysisDetail').textContent='模型已解析 '+s.model_progress.completed+' / '+s.model_progress.total+' 种原文（相同原文复用分类）。'+(s.message||'');if(running){analysisTimer=setTimeout(()=>pollAnalysis(id),2000);return}
if(s.status==='completed'){$('error').textContent='';const [r,v]=await Promise.all([api(wb('report',id)),api(wb('review',id))]);if(id!==activeId)return;R=r;rawComments=null;review=v;renderReport();$('analysisDetail').textContent='已准备 '+s.comments+' 条原始弹幕与 '+s.frames+' 张画面。'+(R.analysis_status==='model_preliminary'?R.method_note:ANALYSIS_PLACEHOLDER)}}catch(e){fail(e);$('analyze').disabled=false}}
function maskedReport(data){if(data.analysis_status==='model_preliminary')return data;const copy=JSON.parse(JSON.stringify(data));copy.analysis_status='awaiting_model';copy.method_note=ANALYSIS_PLACEHOLDER;copy.comments=copy.comments.map(c=>({id:c.id,text:c.text,playback_ms:c.playback_ms,source_row:c.source_row,labels:[],questions:[],positive:false,candidate_segment_ids:[],association_status:ANALYSIS_PLACEHOLDER,method:ANALYSIS_PLACEHOLDER}));copy.summary=null;copy.questions=[];copy.groups=[];copy.wordcloud=[];copy.label_counts=Object.fromEntries(Object.keys(copy.label_counts).map(k=>[k,null]));copy.positive_comment_ids=[];copy.question_count=null;copy.segments=[];copy.timeline=copy.timeline.map(b=>({start_ms:b.start_ms,end_ms:b.end_ms,count:b.count}));return copy}
function renderReport(){R=maskedReport(R);questionLimit=20;segmentLimit=20;chartKey='count';$('report').hidden=false;let scope=$('analysisScopeNote');if(!scope){scope=el('p',undefined,'muted');scope.id='analysisScopeNote';$('report').prepend(scope)}const sc=R.analysis_scope;scope.textContent=sc?'分析范围 00:00–'+Math.floor(sc.end_s/60)+':'+String(Math.round(sc.end_s%60)).padStart(2,'0')+'；纳入 '+sc.selected_comment_count+' / '+sc.source_comment_count+' 条已取得弹幕。'+(sc.sample_size?'抽样试跑，不代表范围内反馈比例。':'范围外内容未作评价。'):'';$('method').textContent=ANALYSIS_PLACEHOLDER;$('reportMetrics').replaceChildren();metric('reportMetrics','纳入分析的弹幕',R.comments.length.toLocaleString(),'条 · 已取得快照');for(const title of ['含问题的弹幕','问题单元','积极表达']){const d=el('div',undefined,'metric');d.append(el('span',title),el('p',ANALYSIS_PLACEHOLDER,'model-placeholder'));$('reportMetrics').append(d)}
for(const id of ['focusWindows','cloud','questions','segments'])$(id).replaceChildren(el('p',ANALYSIS_PLACEHOLDER,'model-placeholder'));
$('labels').replaceChildren();for(const label of Object.keys(R.label_counts)){const d=el('div',undefined,'model-label');d.append(el('span',label),el('p',ANALYSIS_PLACEHOLDER,'model-placeholder'));$('labels').append(d)}
for(const id of ['positive','emotionOnly','questionChart','questionSearch','segmentSearch']){$(id).disabled=true;$(id).title=ANALYSIS_PLACEHOLDER}
$('moreQuestions').hidden=true;$('moreSegments').hidden=true;$('contextNote').textContent=ANALYSIS_PLACEHOLDER;$('segmentCount').textContent='';
$('exportReport').href=wb('export');$('exportReport').onclick=async e=>{e.preventDefault();try{const reviewData=await api(wb('review'));const blob=new Blob([JSON.stringify({...R,teacher_review:reviewData},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=el('a');a.href=u;a.download='course-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(err){fail(err)}};
$('exportHtml').href=wb('html');$('video').src=wb('video');$('video').hidden=!acquisition.artifacts.video;$('playbackStatus').textContent='';$('notes').value=review.notes||'';$('reviewStatus').textContent='';updateReviewCount();drawChart();frameLimit=6;renderCurriculum();renderMedia();if(R.analysis_status==='model_preliminary')renderModelReport();}
function drawChart(){if(!R)return;$('chart').replaceChildren();const max=Math.max(1,...R.timeline.map(b=>b[chartKey]));for(const bin of R.timeline){const cs=R.comments.filter(c=>c.playback_ms>=bin.start_ms&&(c.playback_ms<bin.end_ms||(bin.end_ms===Math.round(R.course.duration_s*1000)&&c.playback_ms===bin.end_ms))&&(chartKey==='count'||c.questions.length));const b=button('',()=>showEvidence(cs.map(c=>c.id),fmt(bin.start_ms/1000)+'–'+fmt(bin.end_ms/1000)+' · 反馈依据'));b.style.height=Math.max(3,150*(logScale?Math.log1p(bin[chartKey])/Math.log1p(max):bin[chartKey]/max))+'px';b.title=fmt(bin.start_ms/1000)+' · '+bin[chartKey]+(chartKey==='count'?' 条弹幕':' 个问题单元');b.setAttribute('aria-label',b.title);$('chart').append(b)}$('chartEnd').textContent=fmt(R.course.duration_s);$('scaleChart').setAttribute('aria-pressed',logScale);$('chartNote').textContent=logScale?'纵向采用 log(1+数量) 压缩高峰，便于观察低频反馈。悬停与点击仍显示实际数量。':'每柱为一分钟，点击回看该时间段的原始反馈。';$('countChart').setAttribute('aria-pressed',chartKey==='count');$('questionChart').setAttribute('aria-pressed',chartKey!=='count')}
$('countChart').onclick=()=>{chartKey='count';drawChart()};$('questionChart').onclick=()=>{chartKey='question_count';drawChart()};
$('allFeedback').onclick=()=>showEvidence(R.comments.map(c=>c.id),'全部弹幕');$('positive').onclick=()=>showEvidence(R.positive_comment_ids,'积极表达候选');$('emotionOnly').onclick=()=>showEvidence(R.comments.filter(c=>c.labels.includes('学习情绪')&&!c.questions.length).map(c=>c.id),'情绪表达 · 未识别到提问');
function renderQuestions(){if(!R)return;const query=$('questionSearch').value.trim(),groups=R.groups.filter(g=>g.title.includes(query)).sort((a,b)=>Number(/^[?？\s]+$/.test(a.title))-Number(/^[?？\s]+$/.test(b.title))||b.count-a.count);$('questions').replaceChildren();for(const g of groups.slice(0,questionLimit)){const d=el('article',undefined,'item');d.append(el('p',g.summary),el('p',g.count+' 个问题单元 · '+g.comment_ids.length+' 条依据','muted small'),button('查看逐条依据 ↗',()=>showEvidence(g.comment_ids,g.title)));$('questions').append(d)}$('moreQuestions').hidden=groups.length<=questionLimit;if(!groups.length)$('questions').append(el('p','当前筛选下没有问题。','muted'))}
$('questionSearch').oninput=()=>{questionLimit=20;renderQuestions()};$('moreQuestions').onclick=()=>{questionLimit+=20;renderQuestions()};
async function seek(ms){if(!acquisition?.artifacts?.video){window.open('https://www.bilibili.com/video/'+acquisition.bvid+'/?p='+acquisition.part+'&t='+Math.floor(ms/1000),'_blank','noopener');return}const v=$('video');v.scrollIntoView({block:'center',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});$('playbackStatus').textContent='正在定位 '+fmt(ms/1000)+'…';try{if(!v.readyState){await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{cleanup();reject(Error('视频载入超时，可使用原视频链接回看'))},15000);function cleanup(){clearTimeout(timer);v.removeEventListener('loadedmetadata',ok);v.removeEventListener('error',bad)}function ok(){cleanup();resolve()}function bad(){cleanup();reject(Error('浏览器暂不能解码本地视频，可使用原视频链接回看'))}v.addEventListener('loadedmetadata',ok);v.addEventListener('error',bad);v.load()})}v.currentTime=ms/1000;$('playbackStatus').textContent='已定位 '+fmt(ms/1000)+'，点击播放器播放。'}catch(e){$('playbackStatus').textContent=e.message}}
function renderSegments(){if(!R)return;const list=R.segments.filter(s=>s.text.includes($('segmentSearch').value.trim()));$('segments').replaceChildren();for(const s of list.slice(0,segmentLimit)){const d=el('div',undefined,'item');d.append(button(fmt(s.start_ms/1000)+'–'+fmt(s.end_ms/1000),()=>seek(s.start_ms)),el('p',s.text));const ids=R.comments.filter(c=>c.candidate_segment_ids.includes(s.id)).map(c=>c.id);d.append(button('候选反馈 '+ids.length+' 条',()=>showEvidence(ids,'附近讲解关联的候选反馈')));$('segments').append(d)}$('moreSegments').hidden=list.length<=segmentLimit;}
$('segmentSearch').oninput=()=>{segmentLimit=20;renderSegments()};$('moreSegments').onclick=()=>{segmentLimit+=20;renderSegments()};
function showEvidence(ids,title){evidenceIds=[...new Set(ids)];evidenceLimit=40;$('evidenceTitle').textContent=title;$('evidenceSearch').value='';renderEvidence();$('evidenceDialog').showModal()}
function renderEvidence(){const source=R?.comments||rawComments||[],map=new Map(source.map(c=>[c.id,c])),q=$('evidenceSearch').value.trim(),list=evidenceIds.map(id=>map.get(id)).filter(c=>c&&c.text.includes(q)).sort((a,b)=>a.playback_ms-b.playback_ms);$('evidence').replaceChildren();$('evidenceCount').textContent=list.length+' 条原始依据 · 显示前 '+Math.min(list.length,evidenceLimit)+' 条';
for(const c of list.slice(0,evidenceLimit)){const d=el('article',undefined,'evidence');d.append(el('span',c.id,'tags'),el('blockquote',c.text));const actions=el('div',undefined,'actions');actions.append(button(fmt(c.playback_ms/1000)+' · 定位视频',()=>{if(!R){window.open('https://www.bilibili.com/video/'+acquisition.bvid+'/?p='+acquisition.part+'&t='+Math.floor(c.playback_ms/1000),'_blank','noopener');return}$('evidenceDialog').close();seek(c.playback_ms)}));
if(R){d.append(el('p',R.analysis_status==='model_preliminary'?c.labels.join(' · ')+' · '+c.method:ANALYSIS_PLACEHOLDER,'tags'));for(const sid of c.candidate_segment_ids){const s=R.segments.find(x=>x.id===sid);if(s)d.append(el('p','候选讲解 '+fmt(s.start_ms/1000)+'：'+s.text,'muted small'))}
const frame=(R.frames||[]).map((f,i)=>({...f,index:i})).sort((a,b)=>Math.abs(a.requested_time_s*1000-c.playback_ms)-Math.abs(b.requested_time_s*1000-c.playback_ms))[0];if(frame&&Math.abs(frame.requested_time_s*1000-c.playback_ms)<=120000){const img=el('img');img.src=wb('frame')+'?index='+frame.index;img.loading='lazy';img.alt='附近课程画面 '+fmt(frame.requested_time_s);d.append(img)}
for(const [state,label] of [['confirmed','确认线索'],['rejected','排除误判'],['pending','待核查']]){const b=button(label,async()=>{review.items[c.id]=state;try{await saveReview();renderEvidence()}catch(e){fail(e)}});b.setAttribute('aria-pressed',review.items[c.id]===state);actions.append(b)}}d.append(actions);$('evidence').append(d)}$('moreEvidence').hidden=list.length<=evidenceLimit;}
$('evidenceSearch').oninput=()=>{evidenceLimit=40;renderEvidence()};$('moreEvidence').onclick=()=>{evidenceLimit+=40;renderEvidence()};$('closeEvidence').onclick=()=>$('evidenceDialog').close();
function updateReviewCount(){const values=Object.values(review.items||{});$('reviewCount').textContent='确认 '+values.filter(x=>x==='confirmed').length+' 条 · 排除 '+values.filter(x=>x==='rejected').length+' 条'}
async function saveReview(){review.notes=$('notes').value;await api(wb('review'),review);updateReviewCount();$('reviewStatus').textContent='已保存到本机项目';}
$('saveReview').onclick=()=>saveReview().catch(fail);
let connection=null,qrExpires=0;
const connectionNames={disconnected:'未连接',waiting_scan:'等待扫码',waiting_confirm:'已扫码 · 等待确认',qr_expired:'二维码已过期',connected:'已验证连接',expired:'会话未登录或已失效',verification_failed:'验证暂不可用'};
function drawConnection(d){connection=d;const badge=d.verification_stale?'需要重新验证':(connectionNames[d.state]||'状态待确认');$('connectionBadge').textContent=badge;$('connectionBadge').dataset.connected=String(d.logged_in&&!d.verification_stale);$('loginStatus').textContent=badge;$('connectionMessage').textContent=d.message;$('login').textContent=d.logged_in?'B站 · '+badge:'连接 B站';$('accountName').textContent=d.profile?.name||'尚未连接账号';$('accountSymbol').textContent=d.profile?.name?.slice(0,1)||'B';$('accountDetail').textContent=d.profile?['UID '+(d.profile.uid||'未返回'),d.profile.level!==null&&d.profile.level!==undefined?'等级 Lv.'+d.profile.level:null].filter(Boolean).join(' · '):'通过官方扫码验证后显示账号信息';$('checkedAt').textContent=d.checked_at?new Date(d.checked_at).toLocaleString():'尚未验证';$('accessMode').textContent=d.logged_in?'获取时使用已验证本地会话':'公开可访问素材可直接获取';$('connectAccount').textContent=d.logged_in?'切换账号 · 重新扫码':'扫码连接账号 ↗';qrExpires=d.qr_remaining_seconds?Date.now()+d.qr_remaining_seconds*1000:0;updateQrCountdown();}
function updateQrCountdown(){const seconds=Math.max(0,Math.ceil((qrExpires-Date.now())/1000));$('qrCountdown').textContent=seconds?'二维码预计剩余 '+seconds+' 秒，实际状态以官方返回为准':'';}
async function pollLogin(){try{const d=await api('/api/login/poll',{});drawConnection(d);$('qrStatus').textContent=d.message;if(d.logged_in){$('loginDialog').close();return}if($('loginDialog').open&&['waiting_scan','waiting_confirm'].includes(d.state))loginTimer=setTimeout(pollLogin,4000)}catch(e){$('qrStatus').textContent=e.message}}
async function openLogin(){clearTimeout(loginTimer);if(!$('loginDialog').open)$('loginDialog').showModal();$('qrStatus').textContent='正在生成官方二维码…';$('qr').removeAttribute('src');$('officialLogin').removeAttribute('href');$('renewQr').disabled=true;try{const d=await api('/api/login/start',{});drawConnection(d);$('qr').src=d.qr_image;$('officialLogin').href=d.login_url;$('qrStatus').textContent=d.message;pollLogin()}catch(e){$('qrStatus').textContent=e.message}finally{$('renewQr').disabled=false}}
$('login').onclick=()=>connection?.logged_in?$('connectionPanel').scrollIntoView({block:'center'}):openLogin();$('connectAccount').onclick=openLogin;$('renewQr').onclick=openLogin;
$('refreshConnection').onclick=async()=>{const b=$('refreshConnection');b.disabled=true;b.textContent='正在验证…';try{if(connection?.state==='waiting_scan'||connection?.state==='waiting_confirm')drawConnection(await api('/api/login/poll',{}));else drawConnection(await api('/api/login/refresh',{}))}catch(e){$('connectionMessage').textContent=e.message}finally{b.disabled=false;b.textContent='检查连接状态'}};
$('closeLogin').onclick=()=>{clearTimeout(loginTimer);$('loginDialog').close()};$('loginDialog').addEventListener('close',()=>clearTimeout(loginTimer));$('logout').onclick=async()=>{try{clearTimeout(loginTimer);drawConnection(await api('/api/login/clear',{}))}catch(e){fail(e)}};
api('/api/login/status').then(drawConnection).catch(e=>{$('connectionBadge').textContent='状态读取失败';$('connectionMessage').textContent=e.message});
setInterval(()=>{if($('loginDialog').open)updateQrCountdown()},1000);
setInterval(()=>{if(!document.hidden)api('/api/login/status').then(drawConnection).catch(()=>{})},30000);
loadCourses();const requestedCourse=new URLSearchParams(location.search).get('course');if(requestedCourse&&/^[a-f0-9]{32}$/.test(requestedCourse)){selectCourse(requestedCourse).catch(fail)}else api('/api/acquisition/latest').then(d=>{if(d.id)selectCourse(d.id).catch(fail)}).catch(fail);

function renderFocus(){const windows=[];for(let start=0;start<R.course.duration_s*1000;start+=300000){const end=Math.min(start+300000,R.course.duration_s*1000),cs=R.comments.filter(c=>c.playback_ms>=start&&(c.playback_ms<end||(end===R.course.duration_s*1000&&c.playback_ms===end))),qs=cs.filter(c=>c.questions.length);windows.push({start,end,cs,qs})}$('focusWindows').replaceChildren();for(const w of windows.sort((a,b)=>b.qs.length-a.qs.length).slice(0,3)){const d=el('div',undefined,'focus-window');d.append(el('span',fmt(w.start/1000)+'–'+fmt(w.end/1000),'muted'),el('p',w.qs.length+' 条含问题反馈','highlight'),el('p','该窗口共 '+w.cs.length+' 条弹幕','muted small'),button('回看问题依据 ↗',()=>showEvidence(w.qs.map(c=>c.id),'优先复盘 · '+fmt(w.start/1000))));$('focusWindows').append(d)}}

$('scaleChart').onclick=()=>{logScale=!logScale;drawChart()};

function drawAcquisitionProgress(d){const area=$('acquisitionProgress'),stages=d.stages||[],keys=['metadata','danmaku','video','video_validation'];const total=d.status==='snapshot_acquired'?2:4;const complete=keys.slice(0,total).filter(k=>stages.some(s=>s.name===k&&s.status==='completed')).length;const success=['acquired','snapshot_acquired'].includes(d.status),running=d.status==='running';const current=[...stages].reverse().find(s=>s.status==='running');const failed=stages.find(s=>s.status==='failed');area.hidden=false;area.dataset.state=success?'success':running?'running':d.status==='partial'?'partial':'failed';$('refreshAcquisition').hidden=true;$('acquisitionState').textContent=success?'✓ 获取成功':running?'◌ 正在获取':d.status==='partial'?'! 部分获取成功':'× 获取失败';$('stageCount').textContent='已完成 '+complete+' / '+total+' 个阶段';$('stageProgress').max=total;$('stageProgress').value=complete;$('stageProgress').setAttribute('aria-valuetext','已完成 '+complete+' 个阶段，共 '+total+' 个');$('progressDetail').textContent=success?'所列素材已保存并校验，可以继续生成反馈报告。':running?(current?'当前：'+(names[current.name]||current.name)+'。':'正在准备获取任务。')+' 上方表示已完成阶段，不是预计耗时百分比。':(failed?'未完成阶段：'+(names[failed.name]||failed.name)+'。':'')+(d.error||'请查看获取记录。');const video=stages.find(s=>s.name==='video'&&s.status==='running');$('fileProgressArea').hidden=!running||!video||current?.name==='video_validation';if(running&&video){const downloaded=Number(video.downloaded_bytes)||0,totalBytes=Number(video.total_bytes)||0;const bar=$('fileProgress');if(totalBytes>0){const percent=Math.min(100,100*downloaded/totalBytes);bar.value=percent;$('fileProgressLabel').textContent='当前文件下载 · 约 '+percent.toFixed(1)+'%';$('fileBytes').textContent=(downloaded/1048576).toFixed(1)+' / '+(totalBytes/1048576).toFixed(1)+' MiB（总量可能为估计值）';if(percent>=100)$('progressDetail').textContent='当前文件已下载，正在处理其余音轨或合并校验；全部成功后才会显示获取成功。'}else{bar.removeAttribute('value');$('fileProgressLabel').textContent='正在获取音视频 · 总量待确定';$('fileBytes').textContent=downloaded?'已下载 '+(downloaded/1048576).toFixed(1)+' MiB':''}}}
$('refreshAcquisition').onclick=()=>{if(activeId)pollAcquisition(activeId)};

function modelCitations(parent,items){for(const item of items||[]){const d=el('article',undefined,'item');d.append(el('p',item.text));const ids=(item.evidence_ids||[]).filter(id=>R.comments.some(c=>c.id===id));if(ids.length)d.append(button('查看 '+ids.length+' 条弹幕依据',()=>showEvidence(ids,'模型结论依据')));for(const id of item.evidence_ids||[]){const k=(R.chapters||[]).find(k=>k.id===id),s=R.segments.find(s=>s.id===id),f=(R.frames||[]).find(f=>f.id===id),o=R.syllabus?.paragraphs.find(o=>o.id===id);if(k)d.append(button(id+' · '+k.title,()=>seek(k.start_ms)));if(s)d.append(button(id+' · '+s.text,()=>seek(s.start_ms)));if(f)d.append(button(id+' · 课堂画面',()=>seek(f.requested_time_s*1000)));if(o)d.append(el('blockquote',id+' · '+o.text));}parent.append(d)}}
function renderModelReport(){
 $('method').textContent=R.method_note;$('reportMetrics').replaceChildren();metric('reportMetrics','弹幕快照',R.comments.length.toLocaleString(),R.analysis_scope?.sample_size?'条 · 抽样输入':'条 · 全部输入');metric('reportMetrics','含问题的弹幕',R.summary.question_comments,'条 · 模型与规则候选');metric('reportMetrics','问题单元',R.question_count,'个 · 保留原文');metric('reportMetrics','积极表达',R.summary.positive_comments,'条 · 模型候选');
 $('labels').replaceChildren();for(const [label,n] of Object.entries(R.label_counts)){const b=button('',()=>showEvidence(R.comments.filter(c=>c.labels.includes(label)).map(c=>c.id),label));b.append(el('span',label),el('strong',n));$('labels').append(b)}
 for(const id of ['positive','emotionOnly','questionChart','questionSearch','segmentSearch']){$(id).disabled=false;$(id).title='模型初步分析，待人工复核'}
 $('cloud').replaceChildren();for(const w of R.wordcloud){const ids=R.questions.filter(q=>w.question_ids.includes(q.id)).map(q=>q.comment_id),b=button(w.term+' '+w.count,()=>showEvidence(ids,w.term+' · 原问题依据'));b.style.fontSize=(14+Math.min(20,Math.log1p(w.count)*5))+'px';$('cloud').append(b)}if(!R.wordcloud.length)$('cloud').append(el('p','当前已识别问题未提取到可核验原文主题词。'));
 renderQuestions();renderSegments();$('segmentCount').textContent=R.segments.length+' 段转写草稿';$('contextNote').textContent='转写可能误识别术语与公式；时间邻近关联仍需核对。';
 $('focusWindows').replaceChildren(el('p',R.model_review?.overview||''),el('p','综合复盘选取 '+(R.synthesis_comment_ids||[]).length+' 条代表反馈；全部已识别问题在下方保留。','muted small'));const unresolved=R.comments.filter(c=>c.model_unresolved);if(unresolved.length)$('focusWindows').append(button(unresolved.length+' 条模型未完成分类 · 查看待处理原文',()=>showEvidence(unresolved.map(c=>c.id),'模型未完成分类')));modelCitations($('focusWindows'),R.model_review?.findings);
 $('courseStructure').replaceChildren();for(const k of R.chapters||[]){const d=el('article',undefined,'item');d.append(button(fmt(k.start_ms/1000)+'–'+fmt(k.end_ms/1000)+' · '+k.title,()=>seek(k.start_ms)));modelCitations(d,k.points);$('courseStructure').append(d)}if(!R.chapters?.length)$('courseStructure').append(el('p','本次未输入音视频，未生成课程主题。'));
 $('outlineAlignment').replaceChildren();if(R.syllabus_stale)$('outlineAlignment').append(el('p','教学大纲已更新，请重新生成报告以建立新的对应。'));else if(!R.syllabus)$('outlineAlignment').append(el('p','尚未提供教师教学大纲；本次仅进行讲解与反馈复盘。'));else modelCitations($('outlineAlignment'),R.model_review?.alignment);
 $('goalFeedback').textContent='依据引用区分教师原文、讲解主题和弹幕；对应关系为模型建议，需教师确认。';$('integratedSuggestions').replaceChildren();modelCitations($('integratedSuggestions'),R.model_review?.findings);
}
async function refreshModel(){try{const d=await api('/api/model/status');const p=$('inferenceProvider').value;const profile=d.profiles?.[p];if(p==='campus'){$('modelState').textContent='【待真实接入测试】';return}$('modelState').textContent=p==='local'?(d.connected?'本地模型已连接 · 初步分析待复核':'本地模型未启动'):(profile?.configured?'服务已配置 · 调用结果待验证':'请先配置'+(p==='api'?' API':'校园模型')+'地址、模型与密钥');}catch{$('modelState').textContent='暂无法确认模型状态'}}
$('inferenceProvider').onchange=refreshModel;
refreshModel();setInterval(refreshModel,15000);

let apiPresets={};
function renderApiStatus(d){$('apiKeyState').textContent=d.key_status+(d.checked_at?' · 最近验证 '+new Date(d.checked_at).toLocaleString():'')+((d.models||[]).length?' · '+d.models.length+' 个候选模型':'');$('apiUsage').textContent='当前连接课镜 API：'+d.requests+' 次返回 · 输入 '+d.input_tokens+' Token · 输出 '+d.output_tokens+' Token'+(d.missing_usage?'；其中 '+d.missing_usage+' 次未返回完整用量':'')+'（非账户总用量）';$('apiBalanceState').textContent='余额：'+d.balance;const list=$('apiModels');list.replaceChildren();for(const id of d.models||[]){const o=el('option');o.value=id;list.append(o)}}
function vendorChanged(){const p=apiPresets[$('apiVendor').value];if(!p)return;$('apiUrl').value=p.url;$('apiVendorNote').textContent=p.note;$('apiDocs').href=p.docs||'#';$('apiDocs').hidden=!p.docs;$('apiKey').value='';$('apiModel').value='';$('apiModels').replaceChildren();$('apiError').textContent='更改厂商后请重新保存连接；当前运行配置以保存结果为准。'}
async function apiAction(action,data={}){const buttons=[...$('apiSettings').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('apiError').textContent='处理中…';try{const d=await api('/api/model/'+action,data);renderApiStatus(d);$('apiError').textContent='';if(action==='configure'||action==='clear')$('apiKey').value='';await refreshModel()}catch(e){$('apiError').textContent=e.message;try{renderApiStatus(await api('/api/model/settings'))}catch{}}finally{buttons.forEach(b=>b.disabled=false)}}
$('apiVendor').onchange=vendorChanged;
$('saveApi').onclick=()=>apiAction('configure',{vendor:$('apiVendor').value,url:$('apiUrl').value,key:$('apiKey').value,model:$('apiModel').value,format:$('apiFormat').value});
$('fetchModels').onclick=()=>apiAction('models');$('selectApiModel').onclick=()=>apiAction('select',{model:$('apiModel').value});$('testApi').onclick=()=>apiAction('probe');$('apiBalance').onclick=()=>apiAction('balance');$('clearApi').onclick=()=>apiAction('clear');
(async()=>{try{const d=await api('/api/model/settings');apiPresets=d.presets;for(const [id,p] of Object.entries(apiPresets)){const o=el('option',p.name);o.value=id;$('apiVendor').append(o)}$('apiVendor').value=d.vendor||'bailian';vendorChanged();if(d.configured){$('apiUrl').value=d.url;$('apiModel').value=d.model}$('apiError').textContent='';renderApiStatus(d)}catch(e){$('apiError').textContent=e.message}})();
setInterval(async()=>{try{renderApiStatus(await api('/api/model/settings'))}catch{}},15000);
