'use strict';
const $=id=>document.getElementById(id);let me=null,selected=null,comments=[],lastTime=0,seen=new Set(),loadSeq=0,externalService={url:''};
function node(tag,text){const e=document.createElement(tag);e.textContent=text;return e}
function action(text,fn){const b=node('button',text);b.onclick=()=>Promise.resolve(fn()).catch(error);return b}
function error(e){$('notice').textContent=e.message||String(e)}
async function api(path,data){const r=await fetch(path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Demo-Token':window.APP_TOKEN},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求未完成');return d}
async function init(){const d=await api('/api/platform/me');externalService=d.external_service||{url:''};$('externalConsentRow').hidden=!externalService.url;$('externalConsentText').textContent='另行同意将本条弹幕用于 '+externalService.vendor+'（'+externalService.url+'）的教师反馈分析；可不选。';me=d.user;$('account').hidden=!!me;$('signout').hidden=!me;$('identity').textContent=me?me.name+' · '+(me.role==='teacher'?'教师':'学习者'):'尚未登录';$('analysisLink').hidden=me?.role!=='teacher';$('uploadPanel').hidden=me?.role!=='teacher';$('setupNote').textContent=d.setup?'首次使用：注册首个教师管理账号。':'使用昵称与密码登录，或注册学习者账号。';await catalog()}
for(const [id,endpoint] of [['signin','login'],['signup','register']])$(id).onclick=async()=>{try{await api('/api/platform/'+endpoint,{name:$('name').value,password:$('password').value});$('password').value='';$('notice').textContent='';await init()}catch(e){error(e)}};
$('signout').onclick=async()=>{await api('/api/platform/logout',{});$('player').pause();$('player').removeAttribute('src');selected=null;$('classroom').hidden=true;await init()};
async function catalog(){if(!me){$('catalog').replaceChildren(node('p','登录后查看已发布课程。'));return}const d=await api('/api/platform/courses');$('catalog').replaceChildren();for(const c of d.courses){const card=node('article','');card.className='course-card';card.append(node('h3',c.title),node('p',(c.published?'已发布':'草稿')+' · '+c.comment_count+' 条弹幕'));const actions=node('div','');actions.className='actions';actions.append(action('进入课程',()=>openCourse(c)));if(c.owned){actions.append(action(c.published?'下架课程':'发布课程',async()=>{await api('/api/platform/course/'+c.id+'/publish',{published:!c.published});await catalog()}));}card.append(actions);$('catalog').append(card)}if(!d.courses.length)$('catalog').append(node('p',me.role==='teacher'?'上传第一节课程，开始课镜教学。':'暂时没有已发布课程。'))}
$('refreshCourses').onclick=()=>catalog().catch(error);
$('upload').onclick=()=>{const file=$('courseVideo').files[0];if(!file||!$('courseTitle').value.trim()||!$('rights').checked){error(Error('请填写课程标题、选择视频并确认素材权利。'));return}if(file.size>512*1024*1024){error(Error('视频超过512MB'));return}const xhr=new XMLHttpRequest();xhr.open('POST','/api/platform/upload?title='+encodeURIComponent($('courseTitle').value.trim())+'&rights=owned-or-authorized');xhr.setRequestHeader('X-Demo-Token',window.APP_TOKEN);xhr.setRequestHeader('Content-Type','video/mp4');$('upload').disabled=true;$('uploadProgress').hidden=false;$('uploadState').textContent='正在上传…';xhr.upload.onprogress=e=>{if(e.lengthComputable){$('uploadProgress').value=e.loaded/e.total*100;$('uploadState').textContent=e.loaded===e.total?'上传完成，正在校验视频…':'已上传 '+Math.round(e.loaded/e.total*100)+'%'}};xhr.onload=()=>{try{const d=JSON.parse(xhr.responseText);if(xhr.status>=400)throw Error(d.error);$('uploadState').textContent=d.message;$('courseVideo').value='';catalog().catch(error)}catch(e){$('uploadState').textContent='上传未完成';error(e)}finally{$('upload').disabled=false}};xhr.onerror=()=>{$('upload').disabled=false;$('uploadState').textContent='网络中断，上传未完成'};xhr.send(file)};
async function openCourse(c){selected=c;lastTime=0;seen.clear();$('danmakuLayer').replaceChildren();$('lessonTitle').textContent=c.title;$('classroom').hidden=false;$('lessonAnalysis').hidden=!c.owned;$('lessonAnalysis').href='/workspace?course='+c.id;$('player').src='/api/platform/course/'+c.id+'/video';await refreshComments();$('classroom').scrollIntoView({behavior:'smooth'})}
const stamp=t=>Math.floor(t/60000).toString().padStart(2,'0')+':'+Math.floor(t/1000%60).toString().padStart(2,'0');
async function refreshComments(){if(!selected)return;const cid=selected.id,seq=++loadSeq;const d=await api('/api/platform/course/'+cid+'/comments');if(selected?.id!==cid||seq!==loadSeq)return;comments=d.comments;$('commentCount').textContent=comments.length+'条';$('comments').replaceChildren();for(const c of [...comments].sort((a,b)=>b.id-a.id)){const row=node('div','');row.className='comment-item';row.append(action(stamp(c.playback_ms),()=>{$('player').currentTime=c.playback_ms/1000}),node('p',c.text));if(c.mine||selected.owned)row.append(action(c.mine?'撤回':'隐藏',async()=>{await api('/api/platform/course/'+cid+'/withdraw',{id:c.id});await refreshComments()}));$('comments').append(row)}}
$('sendComment').onclick=async()=>{if(!selected)return;try{await api('/api/platform/course/'+selected.id+'/comment',{text:$('commentText').value,playback_ms:Math.round($('player').currentTime*1000),analysis:$('analysisConsent').checked,external:$('externalConsent').checked,external_endpoint:externalService.url});$('commentText').value='';$('externalConsent').checked=false;$('commentState').textContent='弹幕已发送 · '+stamp($('player').currentTime*1000);await refreshComments()}catch(e){error(e)}};
$('player').addEventListener('timeupdate',()=>{const t=$('player').currentTime*1000;$('playTime').textContent=stamp(t);if(t<lastTime||t-lastTime>2500){seen.clear();$('danmakuLayer').replaceChildren()}if(!$('player').paused&&$('showDanmaku').checked){for(const c of comments.filter(c=>c.playback_ms<=t&&c.playback_ms>=t-800&&!seen.has(c.id)).slice(0,5)){seen.add(c.id);const e=node('span',c.text);e.className='bullet';e.style.top=(c.id%6)*32+8+'px';$('danmakuLayer').append(e);e.addEventListener('animationend',()=>e.remove())}}lastTime=t});
$('player').addEventListener('pause',()=>{for(const e of $('danmakuLayer').children)e.style.animationPlayState='paused'});$('player').addEventListener('play',()=>{for(const e of $('danmakuLayer').children)e.style.animationPlayState='running'});$('showDanmaku').onchange=()=>{$('danmakuLayer').hidden=!$('showDanmaku').checked};setInterval(()=>{if(me&&selected&&!document.hidden)refreshComments().catch(error)},4000);init().catch(error);
